language: cpp
sudo: required
compiler:
- gcc
os:
- linux

install:
  - wget https://github.com/PeiMengxin/serial/archive/master.zip -O serial.zip
  - unzip serial.zip
  - cd serial-master 
  - make install_deps
  - source setup.bash
  - make -j8 && sudo make install && sudo ldconfig
  - sudo apt-get update && sudo apt-get install libcv-dev
  - pushd testci && ls
  
script: cmake . && make && ./testci