language: cpp
sudo: required
compiler:
- gcc
os:
- linux

install:
  - wget https://github.com/PeiMengxin/serial/archive/master.zip
  - unzip serial-master.zip
  - cd serial-master && mkdir build && cd build && cmake .. && make && sudo make install && sudo ldconfig

script: cmake . && make