language: cpp
sudo: required
compiler:
- gcc
os:
- linux

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get install -y g++-4.9
  - sudo ln -s gcc-4.9 gcc
  - sudo ln -s g++-4.9 g++
  - sudo apt-get install -y cmake
  - sudo ldconfig
  - g++ --version

script: cmake . && make && ./testci