language: cpp
sudo: required
compiler:
- gcc
os:
- linux

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install -y g++-4.9

script: cmake . && make && ./testci