language: cpp
sudo: required
compiler:
- gcc
os:
- linux

install:
  - wget https://github.com/PeiMengxin/serial/archive/master.zip -O serial.zip
  - unzip serial.zip
  - cd serial-master && make && sudo make install && sudo ldconfig

script: cmake . && make