language: cpp
sudo: required
compiler:
- gcc
os:
- linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
    - cmake

script: cmake . && make && ./testci